(define (domain generated_domain)
  (:requirements :strips :typing)
  (:types character location item - object)
  (:predicates
    (at ?x - object ?l - location)
    (has ?c - character ?i - item)
    (connected ?l1 - location ?l2 - location)
    (alive ?c - character)
    (rescued ?p - character)
  )
  (:action move
    :parameters (?c - character ?from - location ?to - location)
    :precondition (and (at ?c ?from) (connected ?from ?to) (alive ?c))
    :effect (and (not (at ?c ?from)) (at ?c ?to))
  )
  (:action take
    :parameters (?c - character ?i - item ?l - location)
    :precondition (and (at ?c ?l) (at ?i ?l) (alive ?c))
    :effect (and (has ?c ?i) (not (at ?i ?l)))
  )
  (:action rescue
    :parameters (?c - character ?p - character ?l - location)
    :precondition (and (at ?c ?l) (at ?p ?l) (alive ?c))
    :effect (rescued ?p)
  )
)